openapi: 3.0.3
info:
  title: API de Gerenciamento de Contatos
  description: API para gerenciamento de contatos
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor de desenvolvimento
paths:
  /contacts:
    get:
      summary: Lista todos os contatos
      operationId: getAllContacts
      responses:
        '200':
          description: Lista de contatos obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContactDTO'
    post:
      summary: Adiciona um novo contato
      operationId: addContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactDTO'
      responses:
        '200':
          description: Contato adicionado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactDTO'
  /contacts/{id}:
    get:
      summary: Obtém detalhes de um contato pelo ID
      operationId: getContactById
      parameters:
        - name: id
          in: path
          description: ID do contato
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes do contato obtidos com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactDTO'
    put:
      summary: Atualiza um contato pelo ID
      operationId: updateContact
      parameters:
        - name: id
          in: path
          description: ID do contato
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactDTO'
      responses:
        '200':
          description: Contato atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactDTO'
    delete:
      summary: Exclui um contato pelo ID
      operationId: deleteContact
      parameters:
        - name: id
          in: path
          description: ID do contato
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Contato excluído com sucesso
components:
  schemas:
    ContactDTO:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 100
          description: Nome do contato
          example: João
        lastName:
          type: string
          maxLength: 100
          description: Sobrenome do contato
          example: Silva
        phone:
          type: string
          maxLength: 15
          description: Telefone do contato
          example: "+55 11 98765-4321"
