openapi: 3.0.3
info:
  title: API de Contatos
  version: 1.0.0
  description: Documentação da API de Contatos
servers:
  - url: http://localhost:8080/api
paths:
  /contacts:
    get:
      summary: Lista de contatos
      description: Retorna uma lista de contatos cadastrados.
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
    post:
      summary: Criação de contato
      description: Cria um novo contato.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          description: Contato criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
  /contacts/{id}:
    parameters:
      - name: id
        in: path
        description: ID do contato
        required: true
        schema:
          type: integer
    get:
      summary: Detalhes de contato
      description: Retorna os detalhes de um contato pelo ID.
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    put:
      summary: Atualização de contato
      description: Atualiza os detalhes de um contato pelo ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: Contato atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    delete:
      summary: Exclusão de contato
      description: Exclui um contato pelo ID.
      responses:
        '204':
          description: Contato excluído com sucesso
components:
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
      required:
        - firstName
        - lastName
        - phone
