openapi: 3.0.3
info:
  title: Phonebook API
  description: RESTful API for managing contacts in a phonebook
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /contacts:
    get:
      summary: Get all contacts
      operationId: getAllContacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
    post:
      summary: Add a new contact
      operationId: addContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
  /contacts/{id}:
    get:
      summary: Get a contact by ID
      operationId: getContactById
      parameters:
        - name: id
          in: path
          description: ID of the contact
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    put:
      summary: Update a contact by ID
      operationId: updateContact
      parameters:
        - name: id
          in: path
          description: ID of the contact
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    delete:
      summary: Delete a contact by ID
      operationId: deleteContact
      parameters:
        - name: id
          in: path
          description: ID of the contact
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
components:
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          maxLength: 100
        lastName:
          type: string
          maxLength: 100
        phone:
          type: string
          maxLength: 15
